"""Tests for what `nanohpc deploy` prepares before running Ansible (inventory, variables, files)."""

import json
import tempfile
import unittest
from pathlib import Path

import yaml

from nanohpc.config import load_config
from nanohpc.deploy import SLURM, prepare

ROOT = Path(__file__).resolve().parents[1]


class PrepareTest(unittest.TestCase):
    """The work folder holds everything Ansible needs, generated from cluster.yml."""

    def setUp(self) -> None:
        config, errors = load_config(ROOT / "examples" / "cluster.yml")
        assert errors == [], errors
        self.config = config
        self.hostnames = {name: f"host-{name}" for name in config["machines"]}
        self.temporary = tempfile.TemporaryDirectory()
        self.work = Path(self.temporary.name)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def test_inventory_groups_follow_roles(self) -> None:
        prepare(self.config, self.hostnames, None, True, ["gpu4", "gpu2", "gpu4i"], self.work)
        groups = yaml.safe_load((self.work / "inventory.yml").read_text())["all"]["children"]
        self.assertEqual(sorted(groups["role_front"]["hosts"]), ["front"])
        self.assertEqual(sorted(groups["role_home"]["hosts"]), ["front"])
        self.assertEqual(sorted(groups["role_backup"]["hosts"]), ["store"])
        self.assertEqual(sorted(groups["role_compute"]["hosts"]), ["cpu1", "gpu2", "gpu4", "gpu4i"])
        self.assertEqual(sorted(groups["role_slurm"]["children"]), ["role_compute", "role_front"])

    def test_variables(self) -> None:
        prepare(self.config, self.hostnames, None, True, ["gpu2"], self.work)
        variables = json.loads((self.work / "vars.json").read_text())["nanohpc"]
        self.assertEqual(variables["cluster_name"], "labcluster")
        self.assertEqual([user["name"] for user in variables["users"]], ["alice", "bob"])
        self.assertEqual(variables["admins"], ["alice"])
        # Only real GPUs are checked with nvidia-smi.
        self.assertEqual(variables["real_gpus"], {"gpu4": 4, "gpu4i": 4})
        # Fake GPUs get placeholder device files.
        self.assertEqual(variables["fake_gpus"], {"gpu2": 2})
        self.assertEqual(variables["max_gpus_per_user"], -1)
        self.assertEqual(variables["slurm"]["version"], SLURM["version"])
        self.assertEqual(variables["files"], str(self.work / "files"))

    def test_files_are_written(self) -> None:
        prepare(self.config, self.hostnames, None, True, ["gpu4", "gpu2", "gpu4i"], self.work)
        files = self.work / "files"
        self.assertIn("NodeHostname=host-gpu4", (files / "slurm.conf").read_text())
        self.assertEqual((files / "gres" / "gpu2.conf").read_text(), "Name=gpu Type=rtx6000ada File=/dev/nvidia[0-1]\n")
        self.assertEqual((files / "gres" / "cpu1.conf").read_text(), "")
        self.assertTrue((files / "job_submit.lua").read_text().startswith("-- Generated by nanoHPC"))
        self.assertIn("192.168.104.20 store\n", (files / "hosts").read_text())

    def test_ssh_config_is_passed_to_ansible(self) -> None:
        ssh_config = self.work / "ssh_config"
        prepare(self.config, self.hostnames, ssh_config, True, [], self.work)
        self.assertIn(f"-F {ssh_config}", (self.work / "ansible.cfg").read_text())
        prepare(self.config, self.hostnames, None, False, [], self.work)
        self.assertNotIn("-F ", (self.work / "ansible.cfg").read_text())


if __name__ == "__main__":
    unittest.main()
